### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by tysoncadenhead** [bigtestjs/bigtestjs.io#59]
Does Bigtest have support for Typescript? If so, are there any additional setup steps I need to take to import ts and tsx files?

**Comment by Robdel12** [comment]
Hey @tysoncadenhead! Thanks for opening an issue :) 

We don't have any support Typescript, but if you would like to create a community supported version of types that would be welcomed with open arms (and I'm sure other folks who use TS would appreciate it!).

We don't really have any plans to add TS to anything BigTest proper since neither of us use TS. A while back someone contributed some types to the convergence package [but we had to remove it since it got out of date quickly. ](https://github.com/bigtestjs/convergence/issues/15) We'd rather have a community version that would be well maintained rather than us forgetting to update the defs :)
